apiVersion: apps/v1
kind: Deployment
metadata:
  name: campaign-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: campaign-service
  template:
    metadata:
      labels:
        app: campaign-service
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: campaign-service
        image: ghcr.io/fatpat117/campaign-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4002
        envFrom:
        - secretRef:
            name: backend-env
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: backend-env
              key: MONGO_URI_CAMPAIGNS
---
apiVersion: v1
kind: Service
metadata:
  name: campaign-service
spec:
  selector:
    app: campaign-service
  ports:
    - port: 4002
      targetPort: 4002

